#! /bin/sh
################################################################################
# Copyright (c) 2011 Krell Institute. All Rights Reserved.
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; either version 2 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc., 59 Temple
# Place, Suite 330, Boston, MA  02111-1307  USA
################################################################################

if [ -z $CBTF_PREFIX ]; then
    export CBTF_PREFIX=$HOME/INSTALL
fi

echo "    "
echo "Building and installing the CBTF Framework into $CBTF_PREFIX ..."
echo "    "

cd libcbtf
./bootstrap
./configure --prefix=$CBTF_PREFIX
make install
cd ..

cd libcbtf-xml
./bootstrap
./configure --prefix=$CBTF_PREFIX \
    --with-cbtf=$CBTF_PREFIX
make install
cd ..

cd libcbtf-mrnet
./bootstrap
if [ -f $CBTF_PREFIX/bin/mrnet_commnode ]; then
    mrnet_option="--with-mrnet=$CBTF_PREFIX"
else
    mrnet_option=""
fi
./configure --prefix=$CBTF_PREFIX $mrnet_option \
    --with-cbtf=$CBTF_PREFIX \
    --with-cbtf-xml=$CBTF_PREFIX
make install
cd ..

echo "    "
echo "Finished building and installing CBTF Framework into $CBTF_PREFIX !"
echo "    "
